config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'
  resources :users do
    resources :exercises
  end
  resources :dashboard, only: :index do
    collection do
      post :search, to: 'dashboard#search'
      get :search, to: 'dashboard#search'
    end
  end
  get :exercises_in_7_days, to: 'charts#exercises_in_7_days', as: :exercises_in_7_days

  resources :friendships, only: [:show, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  ## associations
  belongs_to :user

  # validations
  validates :workout_date, :workout_details, :duration_in_minute, presence: true
  validates :duration_in_minute, numericality: { greater_than: 0}

  # alias attributes
  alias_attribute :workout, :workout_details
  alias_attribute :activity_date, :workout_date

  scope :last_7_days, -> { where('workout_date > ?', 7.days.ago).order(workout_date: :desc)}
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  ## associations
  has_many :exercises, :dependent => :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, class_name: "User"

  ## validations
  validates :first_name, :last_name, presence: true

  # instance methods
  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  ## class methods
  def self.search_by_name(name)
    name_array = name.split(' ')
    if name_array.size == 1
      where('first_name ILIKE ? or last_name ILIKE ?', "%#{name_array[0]}%", "%#{name_array[0]}%")
    else
      where('first_name ILIKE ? or last_name ILIKE ?', "%#{name_array[0]}%", "%#{name_array[1]}%")
    end
  end

  def follows_or_same?(new_friend)
    friendships.map(&:friend).include?(new_friend) or self == new_friend
  end

  ## scopes
  scope :last_7_days, -> { joins(:exercises).where("exercises.created_at between ? and ? and users.id = ?", Time.now - 7.day, Time.now, self.id) }

  # default pagination
  self.per_page = 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def exercises_in_7_days
    render json: Exercise.last_7_days.pluck(:workout_date, :duration_in_minute)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @athletes = User.paginate(page: params[:page])
  end

  def search
    @athletes = User.search_by_name(params[:search_name]).paginate(page: params[:page])
  end

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise,  only: [:show, :edit, :update, :destroy]

  def index
    @exercises = current_user.exercises.last_7_days
  end

  def new
    @exercise = current_user.exercises.new
  end

  def create
    @exercise = current_user.exercises.new(exercise_params)
    if @exercise.save
      flash[:notice] = 'Exercise has been created'
      redirect_to user_exercise_path(current_user, @exercise.id)
    else
      flash[:alert] = 'Exercise has not been created'
      render :new
    end
  end

  def update
    if @exercise.update(exercise_params)
      flash[:notice] = 'Exercise has been updated'
      redirect_to user_exercise_path(current_user, @exercise.id)
    else
      flash[:alert] = 'Exercise has not been updated'
      render :edit
    end
  end

  def show
    # @exercise = current_user.exercises.find(params[:id])
  end

  def edit
    # @exercise = Exercise.find(params[:id])
  end

  def destroy
    @exercise.destroy
    flash[:notice] = 'Exercise has been destroyed'
    # redirect_to [current_user, :exercises]
    redirect_to user_exercises_path
  end

  private

  def set_exercise
    @exercise = current_user.exercises.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:duration_in_minute, :activity_date, :workout, :user_id)
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    friend = User.find(params[:friend_id])

    params[:user_id] = current_user.id
    Friendship.create(friendship_params) unless current_user.follows_or_same?(friend)
    redirect_to root_path
  end

  def edit

  end

  def friendship_params
    params.permit(:friend_id, :user_id)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :first_name, :last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/dashboard/index.html.erb
<div class="jumbotron">
  <h1>Workout Lounge!</h1>
  <% if user_signed_in? %>
    <p>user: <%= current_user.full_name %></p>
  <% end %>
  <p>Show off your workout to you friends and family</p>
</div>
<div class="row">
  <div class="col-md-10">
    <h2>List of Members</h2>
    <%= will_paginate @athletes, render: BootstrapPagination::Rails, class: 'pull-left paginate' %>
  </div>
</div>
<div class="row">
  <% @athletes.each do |athlete| %>
    <div class="col-md-10 well member">
      <%= athlete.full_name %>
      <% if user_signed_in?  %>
        <%= link_to "follow", friendships_path(friend_id: athlete.id),
                    method: :post, class: 'btn btn-success float-right', local: true unless current_user.follows_or_same?(athlete)  %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/dashboard/search.html.erb
<div class="row search-result">
  <% @athletes.each do |athlete| %>
    <div class="col-md-10 col-md-offset- well member">
      <%= athlete.full_name %>
    </div>
  <% end %>
</div>
<%= will_paginate @athletes, render: BootstrapPagination::Rails, class: 'pull-left paginate' %>

app/views/exercises/_form.html.erb
<%= form_with(url: [current_user, @exercise], model: @exercise, html: {class: 'form-horizontal', role: 'form'}, local: true) do |f| %>
  <% if @exercise.errors.any? %>
    <div class="error_explaination">
      <h2><%= pluralize(@exercise.errors.count, 'error') %>
        prohibited the exercise to be saved.</h2>
      <ul>
        <% @exercise.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :duration_in_minute, 'Duration (min)' %>
    <%= f.number_field :duration_in_minute, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :workout, 'Workout Details' %>
    <%= f.text_area :workout, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :activity_date, 'Activity date' %>
    <%= f.date_field :activity_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1 class="text-center">Editing Exercise for <%= current_user.full_name %></h1>
<%= render 'form' %>
<%= link_to 'Back', user_exercise_path(current_user), class: 'btn btn-link' %>

app/views/exercises/index.html.erb
<div class="col-md-8 col-xs-12">
  <%= link_to 'New Workout', new_user_exercise_path(current_user), class: 'btn btn-success' %>
  <% unless @exercises.empty? %>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th>Duration (min)</th>
          <th>Workout Details</th>
          <th>Activity Date</th>
          <td colspan="3"></td>
        </tr>
        </thead>
        <tbody>
        <% @exercises.each do |exercise| %>
          <tr>
            <td><%= exercise.duration_in_minute %></td>
            <td><%= exercise.workout_details %></td>
            <td><%= exercise.activity_date %></td>
            <td>
              <%= link_to 'Edit', [:edit, current_user, exercise] %> |
              <%= link_to 'Show', [current_user, exercise] %> |
              <%= link_to 'Destroy', [current_user, exercise], method: :delete, data: { confirm: 'Are you sure?'} %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <% else %>
    <div>
      <h1>No workout Found! </h1>
    </div>
  <% end %>
  <h1>Duration vs workout</h1>
  <%= line_chart exercises_in_7_days_path, refresh: 80, xtitle: 'WeekDay', ytitle: 'Duration (min)' %>
</div>

app/views/exercises/new.html.erb
<h1  class="text-center">New Exercise for <%= current_user.full_name %></h1>
<%= link_to 'New Workout', 'New Workout' %>
<%= render 'form' %>
<div class="row">
  <div class="col-md-12">
    <div class="col-md-10 col-md-offset-2">
      <%= link_to 'Back', user_exercises_path(current_user), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/exercises/show.html.erb
<h1>Workout Details</h1>
<div class="row">
  <div class="col-md-2">
    <strong>Duration (min)</strong>
  </div>
  <div class="col-md-6">
    <%=  @exercise.duration_in_minute %>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
  <strong>Date</strong>
  </div>
  <div class="col-md-6">
    <%= @exercise.workout_date %>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    <strong>Details</strong>
  </div>
  <div class="col-md-6">
    <%= @exercise.workout_details %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutAppBdd</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: 'share/header' %>
<%= render partial: 'share/main' %>
<%= render partial: 'share/fotter' %>
</body>
</html>

app/views/share/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <!--    <a class="navbar-brand" href="#">Navbar</a>-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Athletes Den', root_path, class: "nav-link" %>
        </li>
      </ul>

      <%= form_with url: search_dashboard_index_path, class: 'form-inline my-2 my-lg-0', local: true, method: :get do |f| %>
        <%= f.text_field :search_name, placeholder: "Search", value: params[:search_name], class: 'form-control mr-sm-2'%>
        <%= f.submit 'search user', class: 'btn btn-outline-success my-2 my-sm-0' %>
      <% end %>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if user_signed_in? %>
            <div class="navbar-right">
              <p class="navbar-text">
                <%= current_user.email %>
              </p>
            </div>
            <li class="nav-item">
              <%= link_to 'My Lounge', user_exercises_path(current_user), class: 'nav-link' %>
            </li>
          <% else %>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          <% end %>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>
            <% else %>
              <%= link_to('Login', new_user_session_path, class: 'nav-link') %>
            <% end %>
          </li>
          </ul>
    </div>
  </nav>
</header>

app/views/share/_main.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key.eql?('notice') ? 'success' : 'danger' %>">
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>